import React from 'react';
import test from 'ava';
import {render} from 'ink-testing-library';
import CaptionedTable from './captioned-table.js';
// NOTE: ESM cannot be imported by import statement
let stripAnsi: (string: string) => string;
(async () => {
	const {default: f} = (await import('strip-ansi')) as {default: unknown};
	stripAnsi = f as (string: string) => string;
	console.dir(stripAnsi);

	tests();
})();

function tests() {
	test('with one colume', t => {
		const data = [{value: 'foo'}];
		const {lastFrame} = render(
			<CaptionedTable title="One column" data={data} />
		);

		// NOTE: combination of `blue` and `bold` generated by ink-table cannot be reproduced by chalk-template,
		//       because those escape sequences are not nested!
		//       (order: "start bold" "start blue" "stop bold" "stop blue")
		t.is(
			stripAnsi(String(lastFrame())),
			` One column
 ┌───────┐
 │ value │
 ├───────┤
 │ foo   │
 └───────┘`
		);
	});
}
